[package]
name = "lottery-dct-meta"
version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dev-dependencies]

[dependencies.lottery-dct]
path = ".."

[dependencies.dharitri-sc-meta]
version = "0.0.1"
